#' Annotate junctions extracted from RNAseq data
#'
#' @param merged_junc data.frame or string The returned data.frame or output file of mergeJuncData function. The coordinates of unique junctions will be used in this function.
#' @param output_prefix string Prefix of output file. The annotations of the junctions will be written in a prefix_anno.txt.gz file.
#' @param reference string The directory to genomic annotation files, which can be generated by prepareGenoRef function. Default to pre-made ensembl annotation version GRCh38.98.
#' @param addition_annotation list or NULL Optional. Name and file name of additional junction annotation source. Default: list(snaptron = system.file("extdata/Reference/snaptron_gtex_anno.txt", package = "SpliPath")). Whether the input junctions are the given junction list will be shown in the output file (in column "in.annotation_name").
#'
#' @import bedr
#' @export
annotateJunc <-
function(merged_junc, output_prefix, reference = "Default", 
         addition_annotation = list(snaptron = system.file(paste("extdata", "Reference", "snaptron_gtex_anno.txt", sep=.Platform$file.sep), package = "SpliPath")) ){
  
  options(scipen = 999)
  if (reference == "Default"){
    gene_ref = system.file(paste("extdata", "Reference", "Gene_GRCh38.98.bed", sep=.Platform$file.sep), package = "SpliPath")
    intron_coding = system.file(paste("extdata", "Reference", "Intron_GRCh38.98.proteincoding.bed", sep=.Platform$file.sep), package = "SpliPath") 
    intron_noncoding = system.file(paste("extdata", "Reference", "Intron_GRCh38.98.noncoding.bed", sep=.Platform$file.sep), package = "SpliPath") 
  }else{
    gene_ref = paste(reference, "Gene.bed", sep=.Platform$file.sep)
    intron_coding = paste(reference, "Intron_proteincoding.bed", sep=.Platform$file.sep)
    intron_noncoding = paste(reference, "Intron_noncoding.bed", sep=.Platform$file.sep)
  }
  gene_ref = read.table(gene_ref, sep='\t', header=F, stringsAsFactors = F) 
  colnames(gene_ref) = c('chr',  'start', 'end', 'gene.id', 'gene.name', 'strand', 'gene.type')
  protein_coding_gene = gene_ref[gene_ref$gene.type == "protein_coding", "gene.id"]
  gene_ref = gene_ref[, colnames(gene_ref)!="gene.type"]
  
  intron_coding = read.csv(intron_coding, sep='\t', header=F, stringsAsFactors = F) 
  colnames(intron_coding) = c('chr',  'start', 'end', 'transcript.id',  'gene.id', 'strand')
  intron_coding$pos = paste(intron_coding$chr, intron_coding$start, intron_coding$end, intron_coding$strand, intron_coding$gene.id, sep=':')
  intron_coding$start.pos = paste(intron_coding$chr, intron_coding$start, intron_coding$strand, intron_coding$gene.id, sep=':')
  intron_coding$end.pos = paste(intron_coding$chr, intron_coding$end, intron_coding$strand, intron_coding$gene.id, sep=':')
  
  intron_noncoding = read.csv(intron_noncoding, sep='\t', header=F, stringsAsFactors = F)
  colnames(intron_noncoding) = c('chr',  'start', 'end', 'transcript.id',  'gene.id', 'strand', 'biotype')
  intron_noncoding$pos = paste(intron_noncoding$chr, intron_noncoding$start, intron_noncoding$end, intron_noncoding$strand, intron_noncoding$gene.id, sep=':')
  
  ensembl_pos = unique(c(paste(intron_coding$chr, intron_coding$start, intron_coding$end, intron_coding$strand, sep=':'),
                  paste(intron_noncoding$chr, intron_noncoding$start, intron_noncoding$end, intron_noncoding$strand, sep=':')))
  
  if (!is.data.frame(merged_junc)){
    merged_junc = read.table(merged_junc, sep='\t', header = T, stringsAsFactors = F)
    merged_junc = merged_junc[, c('chr', 'start', 'end', 'strand')]
  }
  merged_junc = transform(merged_junc, chr = as.character(chr), start = as.numeric(start), end = as.numeric(end))
  merged_junc$x1 = 0
  merged_junc$x2 = 0
  merged_junc = merged_junc[, c('chr',  'start', 'end', 'x1', 'x2', 'strand')]
  merged_junc = bedr::bedr.sort.region(merged_junc, check.chr=F, check.merge = F)
  gene_ref = bedr::bedr(engine = "bedtools", 
                        input = list(i = gene_ref), 
                        method = "sort", check.chr = FALSE , check.merge=F)
  junc_map = bedr::bedr(engine = "bedtools", 
                        params = "-s -d -D b -t all", 
                        input = list(a = merged_junc, b = gene_ref ), 
                        method = "closest", check.chr = FALSE , check.merge=F)
  rm(merged_junc, gene_ref)
  colnames(junc_map) = c('chr',  'start', 'end', 'read.count', 'sample.count', 'strand', 'chr.map',  'start.map', 'end.map', 'gene.id', 'gene.name', 'strand.map', 'dist')
  junc_map = junc_map[junc_map$dist=="0",]
  junc_map$pos = paste(junc_map$chr, junc_map$start, junc_map$end, junc_map$strand, sep=':')
  length(unique(junc_map$pos[duplicated(junc_map$pos)]))/length(unique(junc_map$pos))
  junc_map$start.pos = paste(junc_map$chr, junc_map$start, junc_map$strand, junc_map$gene.id, sep=':')
  junc_map$end.pos = paste(junc_map$chr, junc_map$end, junc_map$strand, junc_map$gene.id, sep=':')
  
  if (!is.null(addition_annotation)){
    for (addition_anno in names(addition_annotation)){
      addition_anno_pos = read.table(addition_annotation[[addition_anno]], header=F, stringsAsFactors = F)$V1
      anno_colname = paste0("in.", addition_anno)
      junc_map[[anno_colname]] = junc_map$pos %in% addition_anno_pos
    }
  }
  junc_map$in.ensembl = junc_map$pos %in% ensembl_pos
  junc_map$coding.gene = junc_map$gene.id %in% protein_coding_gene
  junc_map$coding.transcript = paste(junc_map$pos, junc_map$gene.id, sep= ':') %in% intron_coding$pos
  junc_map$noncoding.transcript = paste(junc_map$pos, junc_map$gene.id, sep=':') %in% intron_noncoding$pos
  
  junc_map$start.anno = junc_map$start.pos %in% intron_coding$start.pos
  junc_map$end.anno = junc_map$end.pos %in% intron_coding$end.pos
  junc_map$start.map = junc_map$start > junc_map$start.map
  junc_map$end.map = junc_map$end < junc_map$end.map
  
  junc_map$map[junc_map$start.map & junc_map$end.map] = "mapped"
  junc_map$map[!junc_map$start.map | !junc_map$end.map] = "d/a_site_unmapped"
  junc_map$map[!junc_map$start.map & !junc_map$end.map] = "unmapped"
  
  junc_map$event = 'annotated'
  junc_map$event[!junc_map$start.anno & junc_map$end.anno & (junc_map$strand == "+")] = "novel_donor"
  junc_map$event[!junc_map$start.anno & junc_map$end.anno & (junc_map$strand == "-")] = "novel_acceptor"
  junc_map$event[junc_map$start.anno & !junc_map$end.anno & (junc_map$strand == "+")] = "novel_acceptor"
  junc_map$event[junc_map$start.anno & !junc_map$end.anno & (junc_map$strand == "-")] = "novel_donor"
  junc_map$event[junc_map$start.anno & junc_map$end.anno & !junc_map$coding.transcript & !junc_map$noncoding.transcript] = "exon_skipping"
  junc_map$event[!junc_map$coding.transcript & junc_map$noncoding.transcript] = "noncoding_transcript"
  junc_map$event[!junc_map$start.anno & !junc_map$end.anno & !junc_map$noncoding.transcript & !junc_map$in.ensembl] = "novel_d&a_site"
  
  exon_skipping_idx = which(junc_map$event == "exon_skipping")
  exon_skipping_anno = lapply(exon_skipping_idx, FUN = function(idx, junc_map){
    ref_intron_gene = intron_coding[intron_coding$gene.id == junc_map[idx, "gene.id"],]
    start = junc_map[idx, "start"]
    end = junc_map[idx, "end"]
    start_transcript = ref_intron_gene[ref_intron_gene$start == start, "transcript.id"]
    end_transcript = ref_intron_gene[ref_intron_gene$end == end, "transcript.id"]
    span_exon_start = TRUE %in% ((ref_intron_gene$end > start) & (ref_intron_gene$end < end))
    span_exon_end = TRUE %in% ((ref_intron_gene$start > start) & (ref_intron_gene$start < end))
    
    if ((length(intersect(start_transcript, end_transcript)) > 0) & (span_exon_start & span_exon_end)){
      return("exon_skipping")
    }else{return("alternative_intron")}
  },
  junc_map = junc_map
  )
  exon_skipping_anno = unlist(exon_skipping_anno)
  junc_map[exon_skipping_idx, "event"] = exon_skipping_anno
  
  # Select junctions mapped within protein-coding genes
  junc_map = junc_map[junc_map$map == "mapped" & junc_map$coding.gene & junc_map$event != "novel_d&a_site",]
  
  # To remove the less likely map when junctions were mapped to multiple genes
  junc_map = junc_map[!(junc_map$coding.transcript == FALSE & junc_map$noncoding.transcript == FALSE & junc_map$in.ensembl == TRUE),]
  
  output_file = gzfile(sprintf("%s_anno.txt.gz", output_prefix), 'w')
  write.table(junc_map, output_file, row.names = F, col.names = T, sep = "\t", quote = F)
  close(output_file)
}

