#' Match SpliceAI prediction of splice sites gain or loss with observed junctions
#'
#' @param gdb_path string The path to GDB database that store the genotype data from whole genome sequencing. The GDB database should contain SpliceAI prediction table.
#' @param var2junc string or data.frame The output file or data.frame of mapVariantJunc function. One row in the the dataframe is an annotated DNA variant that mapped to a novel junction in a subject's tissues. 
#' @param min_spliceai_score number Minimum SpliceAI delta score. The predictions of splice sites that score higher than the minimum SpliceAI delta score will be matched with observed junctions.
#' @param reference string The directory to genomic annotation files, which can be generated by prepareGenoRef function. Default to pre-made ensembl annotation version GRCh38.98.
#'
#' @return data.frame Column "match_by_threshold" shows whether the prediction of variants matched the corresponding novel junction. "NA" in the column means either the prediction score is under given threshold, or the prediction is a gain of annotated site or a loss of novel site which is out the scope of this function. 
#' The "SG", "SL", "EG", and "EL" in the column names means "start gain", "start loss", "end gain", and "end loss".
#' @import RSQLite
#' @import DBI
#' @export
#'
matchPredNObs <-
function(gdb_path, var2junc, min_spliceai_score, reference = "Default"){
  
  if (reference == "Default"){
    ref_intron = system.file(paste("extdata", "Reference", "Intron_GRCh38.98.proteincoding.bed", sep=.Platform$file.sep), package = "SpliPath")
  }else{
    ref_intron = paste(reference, "Intron.proteincoding.bed", sep=.Platform$file.sep)
  }
  intron_ref = read.csv(ref_intron, sep='\t', header=F, stringsAsFactors = F) 
  colnames(intron_ref) = c('chr',  'start', 'end', 'transcript.id',  'gene.id', 'strand')
  
  intron_ref$intron = paste(intron_ref$chr, intron_ref$start,  intron_ref$end,  intron_ref$strand,  intron_ref$gene.id, sep = ":")
  intron_ref = intron_ref[!duplicated(intron_ref$intron), ]
  intron_ref = subset(intron_ref, select = -c(intron, transcript.id))
  intron_ref$anno_start = paste(intron_ref$chr, intron_ref$start, intron_ref$strand, intron_ref$gene.id, sep = ":")
  intron_ref$anno_end = paste(intron_ref$chr, intron_ref$end, intron_ref$strand, intron_ref$gene.id, sep = ":")
  
  if (!is.data.frame(var2junc)){
    var2junc = read.table(var2junc, header=T, sep="\t", stringsAsFactors = F)
  }
  var2junc = tidyr::separate(var2junc, col="Coordinates_of_novel_junc", into=c("chr", "start", "end", "strand", NA), sep=":", remove = F)
  var2junc = var2junc[, c("VAR_id", "DNA_variant", "Coordinates_of_novel_junc", "Event", "Gene_id", "Gene", "Var_region", "Strand", "chr", "start", "end", "strand")]
  var2junc$VAR_id = as.character(var2junc$VAR_id)
  var2junc = unique(var2junc)
  
  gdb = rvat::gdb(gdb_path)
  spliceai = rvat::getAnno(gdb, VAR_id=var2junc$VAR_id, table="SpliceAI")
  spliceai = subset(spliceai, !is.na(spliceaiSYMBOL))
  spliceai_pred = c("spliceaiDS_AG", "spliceaiDS_AL", "spliceaiDS_DG", "spliceaiDS_DL","spliceaiDP_AG", "spliceaiDP_AL", "spliceaiDP_DG", "spliceaiDP_DL")
  spliceai[, c("POS", spliceai_pred)] = sapply(spliceai[, c("POS", spliceai_pred)], FUN=as.numeric)
  spliceai$MaxDS = apply(spliceai[, spliceai_pred[1:4]], 1, max)  
  spliceai$VAR_id = as.character(spliceai$VAR_id)
  spliceai = subset(spliceai,  MaxDS > 0)
  if (sum(spliceai$MaxDS >= min_spliceai_score) == 0){
    stop("No variants have a SpliceAI score greater then the input 'min_spliceai_score'.")
  }
  
  var2junc = subset(var2junc, Event %in% c("exon_skipping", "novel_donor", "novel_acceptor"))
  
  matched = dplyr::inner_join(var2junc, spliceai, by = c("VAR_id"))
  matched$VAR_id = as.character(matched$VAR_id)
  matched$idx = paste(matched$VAR_id, matched$Coordinates_of_novel_junc, sep=":")

  ### Redefine splice start site and end site at forward strand
  forward_strand = matched$strand == "+"
  matched[forward_strand, "spliceaiEG"] = matched[forward_strand, "POS"] + matched[forward_strand, "spliceaiDP_AG" ] - 1
  matched[forward_strand, "spliceaiEL"] = matched[forward_strand, "POS"] + matched[forward_strand, "spliceaiDP_AL" ] - 1
  matched[forward_strand, "spliceaiSG"] = matched[forward_strand, "POS"] + matched[forward_strand, "spliceaiDP_DG" ]
  matched[forward_strand, "spliceaiSL"] = matched[forward_strand, "POS"] + matched[forward_strand, "spliceaiDP_DL" ]

  matched[forward_strand, c("spliceaiDS_EG", "spliceaiDS_EL", "spliceaiDS_SG", "spliceaiDS_SL")] = matched[forward_strand, c("spliceaiDS_AG", "spliceaiDS_AL", "spliceaiDS_DG", "spliceaiDS_DL")] >= 0.1
  
  ### Redefine splice start site and end site at reverse strand
  reverse_strand = matched$strand == "-"
  matched[reverse_strand, "spliceaiSG"] = matched[reverse_strand, "POS"] + matched[reverse_strand, "spliceaiDP_AG" ]
  matched[reverse_strand, "spliceaiSL"] = matched[reverse_strand, "POS"] + matched[reverse_strand, "spliceaiDP_AL" ]
  matched[reverse_strand, "spliceaiEG"] = matched[reverse_strand, "POS"] + matched[reverse_strand, "spliceaiDP_DG" ] - 1
  matched[reverse_strand, "spliceaiEL"] = matched[reverse_strand, "POS"] + matched[reverse_strand, "spliceaiDP_DL" ] - 1

  matched[reverse_strand, c("spliceaiDS_SG", "spliceaiDS_SL", "spliceaiDS_EG", "spliceaiDS_EL")] = matched[reverse_strand, c("spliceaiDS_AG", "spliceaiDS_AL", "spliceaiDS_DG", "spliceaiDS_DL")] >= 0.1

  matched$spliceaiSG_idx = paste(matched$chr, matched$spliceaiSG, matched$strand, matched$Gene_id, sep=":")
  matched$spliceaiEG_idx = paste(matched$chr, matched$spliceaiEG, matched$strand, matched$Gene_id, sep=":")
  matched$spliceaiSL_idx = paste(matched$chr, matched$spliceaiSL, matched$strand, matched$Gene_id, sep=":")
  matched$spliceaiEL_idx = paste(matched$chr, matched$spliceaiEL, matched$strand, matched$Gene_id, sep=":")
      
  match_sites = paste0("match_", c("SG", "SL", "EG", "EL"))
  score_sites = paste0("spliceai", c("DS_SG", "DS_SL", "DS_EG", "DS_EL"))
  
  matched[, match_sites] = FALSE
  
  ### Prediction on gain of annotated splice site & loss of novel splice site are out of scope
  matched[(matched$spliceaiDS_SG & (matched$spliceaiSG_idx %in% intron_ref$anno_start)), "spliceaiDS_SG"] = FALSE
  matched[(matched$spliceaiDS_EG & (matched$spliceaiEG_idx %in% intron_ref$anno_end)), "spliceaiDS_EG"] = FALSE
  matched[(matched$spliceaiDS_SL & (matched$spliceaiSL_idx %in% intron_ref$anno_start)), "spliceaiDS_SL"] = FALSE
  matched[(matched$spliceaiDS_EL & (matched$spliceaiEL_idx %in% intron_ref$anno_end)), "spliceaiDS_EL"] = FALSE
  
  ### Match lost of annotated sites 
  matched_cryptic_loss_all = subset(matched, (spliceaiDS_SL & (spliceaiSL_idx %in% intron_ref$anno_start)) | (spliceaiDS_EL & (spliceaiEL_idx %in% intron_ref$anno_end)) )
  for (var in unique(matched_cryptic_loss_all$VAR_id)){
    matched_cryptic_loss_var = subset(matched_cryptic_loss_all, VAR_id == var)
    if (sum(matched_cryptic_loss_var$spliceaiDS_SL)>0){
      annotated_end = unique(subset(intron_ref, anno_start %in% matched_cryptic_loss_var$spliceaiSL_idx, select = anno_end))
      matched_cryptic_loss_var_ = subset(matched_cryptic_loss_var, end.pos %in% annotated_end)
      if (nrow(matched_cryptic_loss_var_) > 0){
        matched[matched$idx %in% matched_cryptic_loss_var_$idx, "match_SL"] = TRUE
      }
    }
    if (sum(matched_cryptic_loss_var$spliceaiDS_EL)>0){
      annotated_start = unique(subset(intron_ref, anno_end %in% matched_cryptic_loss_var$spliceaiEL_idx, select = anno_start))
      matched_cryptic_loss_var_ = subset(matched_cryptic_loss_var, start.pos %in% annotated_start)
      if (nrow(matched_cryptic_loss_var_) > 0){
        matched[matched$idx %in% matched_cryptic_loss_var_$idx, "match_EL"] = TRUE
      }
    }
  }
  
  ### Match gained of novel site 
  matched_cryptic_gain = subset(matched, ((!spliceaiSG_idx %in% intron_ref$anno_start) & spliceaiDS_SG & spliceaiSG == start) | ((!spliceaiEG_idx %in% intron_ref$anno_end) & spliceaiDS_EG & spliceaiEG == end) )
  matched[matched$idx %in% matched_cryptic_gain[(matched_cryptic_gain$spliceaiSG == matched_cryptic_gain$start), "idx"], "match_SG"] = TRUE
  matched[matched$idx %in% matched_cryptic_gain[(matched_cryptic_gain$spliceaiEG == matched_cryptic_gain$end), "idx"], "match_EG"] = TRUE

  ### Use provided spliceai score threshold
  matched[matched$strand == "+", c("spliceaiDS_EG", "spliceaiDS_EL", "spliceaiDS_SG", "spliceaiDS_SL")] = matched[matched$strand == "+", c("spliceaiDS_AG", "spliceaiDS_AL", "spliceaiDS_DG", "spliceaiDS_DL")] >= min_spliceai_score
  matched[matched$strand == "-", c("spliceaiDS_SG", "spliceaiDS_SL", "spliceaiDS_EG", "spliceaiDS_EL")] = matched[matched$strand == "-", c("spliceaiDS_AG", "spliceaiDS_AL", "spliceaiDS_DG", "spliceaiDS_DL")] >= min_spliceai_score
  
  matched[(matched$spliceaiDS_SG & (matched$spliceaiSG_idx %in% intron_ref$anno_start)), "spliceaiDS_SG"] = FALSE
  matched[(matched$spliceaiDS_EG & (matched$spliceaiEG_idx %in% intron_ref$anno_end)), "spliceaiDS_EG"] = FALSE
  matched[(matched$spliceaiDS_SL & (matched$spliceaiSL_idx %in% intron_ref$anno_start)), "spliceaiDS_SL"] = FALSE
  matched[(matched$spliceaiDS_EL & (matched$spliceaiEL_idx %in% intron_ref$anno_end)), "spliceaiDS_EL"] = FALSE

  ### Judge match or not by number of matched and mis-matched sites
  matched[, score_sites][ which(matched[, score_sites] == FALSE, arr.ind = T) ] = NA
  matched$matched_site = rowSums((matched[, score_sites] * matched[, match_sites]) > 0, na.rm = T)
  matched$miss_matched_site = rowSums((matched[, score_sites] * matched[, match_sites]) == 0, na.rm = T)
  matched$match_by_threshold[matched$matched_site > 0 & matched$miss_matched_site == 0 ] = "full_match"
  matched$match_by_threshold[matched$matched_site > 0 & matched$miss_matched_site > 0] = "partial_match"
  matched$match_by_threshold[matched$matched_site == 0 & matched$miss_matched_site > 0] = "not_match"
  matched$match_by_threshold[matched$matched_site == 0 & matched$miss_matched_site == 0] = NA
  
  ### Add cryptic exon label if prediction match to discovered cryptic exons
  pred_cryptic_exon = !is.na(matched$spliceaiDS_SG & matched$spliceaiDS_EG) & (matched$spliceaiDS_SG & matched$spliceaiDS_EG) == TRUE
  matched[pred_cryptic_exon, "pred_cryptic_exon"] = paste(matched$chr, matched$spliceaiEG, matched$spliceaiSG, matched$strand, matched$Gene_id, sep=":")[pred_cryptic_exon]
  
  matched
}
